/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSys: typeof import('./src/components/AccountSys.vue')['default']
    Actions: typeof import('./src/components/Actions.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    copy: typeof import('./src/components/dialog/create-password copy.vue')['default']
    CreatePassword: typeof import('./src/components/dialog/create-password.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PasswordDialog: typeof import('./src/components/dialog/password-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavaMnemnic: typeof import('./src/components/dialog/sava-mnemnic.vue')['default']
    SaveMnemnic: typeof import('./src/components/dialog/save-mnemnic.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanRow: typeof import('vant/es')['Row']
    VanSpace: typeof import('vant/es')['Space']
    VantButton: typeof import('vant/es')['tButton']
    VanTextarea: typeof import('vant/es')['Textarea']
    Web3Api: typeof import('./src/components/Web3Api.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
