/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./src/components/account-list.vue')['default']
    AccountSys: typeof import('./src/components/learn/account-sys.vue')['default']
    Actions: typeof import('./src/components/Actions.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    copy: typeof import('./src/components/dialog/create-password copy.vue')['default']
    CreatePassword: typeof import('./src/components/dialog/create-password.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputPassword: typeof import('./src/components/dialog/input-password.vue')['default']
    PasswordDialog: typeof import('./src/components/dialog/password-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Savamnemonic: typeof import('./src/components/dialog/sava-mnemonic.vue')['default']
    Savemnemonic: typeof import('./src/components/dialog/save-mnemonic.vue')['default']
    SaveMnemonic: typeof import('./src/components/dialog/save-mnemonic.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIco: typeof import('vant/es')['Ico']
    VanIcon: typeof import('vant/es')['Icon']
    VanRow: typeof import('vant/es')['Row']
    VanSpace: typeof import('vant/es')['Space']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VantButton: typeof import('vant/es')['tButton']
    VanTextarea: typeof import('vant/es')['Textarea']
    Web3Api: typeof import('./src/components/learn/web3-api.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
